server:
  port: 8081
spring:
#  thymeleaf:
#    cache: false
#    prefix: classpath:/templates/
#    suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mywork_db?useSSL=false
    username: root
    password: lidaxin
  redis:
    host: 127.0.0.1
    port: 6379
mybatis:
  mapper-locations: classpath:/static/mapper/*.xml
  type-aliases-package: club.chillrainqcna.bean